### ISSUE TITLE
Cooking for Blockheads Cooking Table Crash

### ISSUE THREAD

**Issue by ghost** [JadedPacks/MF3Configs#11]
_From @sforzando02 on January 2, 2016 16:53_

http://pastebin.com/HPGBUMKs < here is the log file in the game output. It doesn't actually provide a crash log but recently, whenever I try to access the cooking table (I keep trying to type oven so pastebin says oven but it really is the table) from cooking for blockheads it shuts down my single-player like a multi-player world. I will right click with both an empty hand or with an item in my hand and the screen pops up that says "A fatal error has occured, this connection is terminated" and will then send me to the multiplayer screen looking for a valid server to connect to.

Not sure why it is doing it because as of yesterday, it worked fine. 

I am in version 1.1.35 from the Curse Client.

Thanks for the help!

EDIT: Okay so I did some digging and took all the stuff out of the fridges and found that vanilla wheat seeds are causing the crash. Not sure about the others though.

_Copied from original issue: jadedcat/MF3Configs#28_

**Comment by ghost** [comment]
_From @agentGH72 on January 19, 2016 6:1_

Ok... this is not a fix but I seemed to have found a work around. What I did was craft another Cooking for Blockheads 1 book and then open and close the book. Then I used the cooking table. This seems to keep cooking table from crashing to the multiplayer screen.

**Comment by ghost** [comment]
_From @Moojuiceman on May 23, 2016 22:5_

**Seed soup**, that's the issue. A combination of any seed and Harvestcraft stock is what does it for me. Just having them in my inventory (not in the fridge) causes the issue when opening the table. Seems to happen with any seed that's usable in seed soup.

EDIT: Also happens when opening 'Cooking for blockheads I' as if the GUI can't handle displaying seed soup

**Comment by SirBastol** [comment]
``
[crash-2023-09-20_15.49.13-server.txt](https://github.com/JadedPacks/MF3Configs/files/12678168/crash-2023-09-20_15.49.13-server.txt)
 happens only at my base not my sisters..   its got to do something with. too many items in cupboards or shelves.. or incompatible items. ..  redrafted table. no change..  redid book no change open close book before table no change put book in table no change.. 
 my kitchen cabinets are the same number as my counters.. and are connected by floors 
 counters 8 cabinets 8 fridge stove and sink.  and toaster and cow in a jar with milk 
 
 modpack list for server is.  here https://modrinth.com/modpack/hermitcreateflavors
 
 tps on server is 19.. on average. lowest 15. usually as its just the two or three of us 

we are far enough apart that when she's offline.  her chunks aren't loaded and. I still crash the server. 

using toms storage would be nice to be able to connect it and use it to store food items with proper tags.. 
or filters.. ut toms storage doesn't connect :(. future update ???

**Comment by SirBastol** [comment]
pulled everything out of the cupboards and tables that weren't specifically food .and this fixed it. .
 
**### BUGFIX SUGGESTION :  run a check before attempting a recipe  that if its not a food item with a specific tag like 
#cookable or # food  or #edible.  or #ingredient.   to completely ignore it..  so cupboards can also be storage and not crash when something is  not useable.. .**

**Comment by tecrogue** [comment]
@SirBastol This is for the Magic Farm 3 modpack, not random other packs that are running 1.20.1.

If you think it is a cooking for blockheads issue, they are over at https://github.com/TwelveIterationMods/CookingForBlockheads
